[package]
name = "HabitTool"
version = "0.1.0"
authors = ["Reuben Cornel <reuben.cornel@gmail.com>"]

[dependencies]
rustc-serialize = "0.3.25"
getopts = "0.2.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64-url = "3.0.0"